---
- name: Установка Kubectl и зависимости для модуля kubernetes.core.k8s
  apt:
    name: 
      - kubectl
      - python3-kubernetes
      - python3-yaml
      - python3-jsonpatch
    state: present
    update_cache: yes

- name: Инициализация кластера
  command: kubeadm init

- name: Генерация join command
  command: kubeadm token create --print-join-command
  register: kubeadm_join_command

- name: Сохранение join command в переменную
  set_fact:
    join_command: "{{ kubeadm_join_command.stdout }}"

- name: Убедимся что директория {{ HOME_DIR }}/.kube существует
  file:
    path: "{{ HOME_DIR }}/.kube"
    state: directory
    owner: "{{ USER }}"
    group: "{{ GROUP }}"
    mode: '0775'

- name: Копирование конфиг файл Kubernetes в {{ HOME_DIR }}/.kube/
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ HOME_DIR }}/.kube/config"
    remote_src: yes
    owner: "{{ USER }}"
    group: "{{ GROUP }}"
    mode: '0644' 

- name: Копирование конфиг файла Kubernetes на хост с которого будет осуществляться управление кластером
  fetch:
    src: "{{ HOME_DIR }}/.kube/config"
    dest: "{{ CONTROL_NODE_CONF_DIR }}/config"
    flat: yes

- name: Скачивание манифеста calico
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /tmp/calico.yaml
    mode: '0664'

- name: Установка calico
  kubernetes.core.k8s:
    kubeconfig: "{{ HOME_DIR }}/.kube/config"
    state: present
    src: /tmp/calico.yaml